server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.12.0"
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.2.0"
    - dependency: "com.github.topi314.lavasearch:lavasearch-plugin:1.0.0"
    - dependency: "com.github.topi314.sponsorblock:sponsorblock-plugin:3.0.1"
    # REMOVED incompatible plugins:
    # - dependency: "com.github.topi314.lavalyrics:lavalyrics-plugin:1.0.0"  # INCOMPATIBLE
    # - dependency: "com.dunctebot:skybot-lavalink-plugin:1.7.0"  # INCOMPATIBLE
    # - dependency: "me.duncte123:java-lyrics-plugin:1.6.5"  # INCOMPATIBLE
  server:
    password: "TunixMusicBot123"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      http: true
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
  lavasrc:
    providers:
      - "ytmsearch:%QUERY%"  
      - "ytmsearch:%QUERY%"
      - "scsearch:%QUERY%"
    sources:
      youtube: true
      spotify: false
      applemusic: false
    spotify:
      clientId: ""
      clientSecret: ""
      countryCode: "US"

sentry:
  dsn: ""

logging:
  level:
    root: INFO
    lavalink: INFO
